server:
  port: '8086'
  ssl.key-store-type: 'PKCS12'
  ssl.key-store: '/etc/stempol/certs/keystore.p12'
  ssl.key-store-password: 'zdC3MZNQ4CPBB89mZZ5dwUs6PUJN72R9'
  ssl.key-alias: 'tomcat'
  ssl.keyStoreType: PKCS12
security.require-ssl: true
spring.datasource.url: 'jdbc:postgresql://postgres:5432/stempol_notes'
spring.datasource.username: 'postgres'
spring.datasource.password: 'myMhrtc27WqdUZYTZHgwTfr9f3hWHPaReTQR5XrAwJCFTAzB5G8fdKskbeVfCP6JWwXqN3SUWTFaAGHRhM67SZxuDRM8LYEdvxeJtzujgtNqdksBnCWFfpGu3uBJWDyR'

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.show-sql: true

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
